// <auto-generated />
using FoodModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodModel.Migrations
{
    [DbContext(typeof(FoodSourceContext))]
    [Migration("20240330222303_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodModel.FoodPlace", b =>
                {
                    b.Property<int>("FoodPlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodPlaceId"));

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("FoodPlaceId")
                        .HasName("PK__FoodPlace");

                    b.ToTable("FoodPlace");
                });

            modelBuilder.Entity("FoodModel.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<int>("FoodPlaceId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuItemId")
                        .HasName("PK__MenuItem__8943F7227526083B");

                    b.HasIndex("FoodPlaceId");

                    b.ToTable("MenuItem");
                });

            modelBuilder.Entity("FoodModel.MenuItem", b =>
                {
                    b.HasOne("FoodModel.FoodPlace", "FoodPlace")
                        .WithMany("MenuItems")
                        .HasForeignKey("FoodPlaceId")
                        .IsRequired()
                        .HasConstraintName("FK_MenuItem_FoodPlace");

                    b.Navigation("FoodPlace");
                });

            modelBuilder.Entity("FoodModel.FoodPlace", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
